// SETTINGS CONSTANTS
export const LOGO_BG = 'LOGO_BG';
export const NAVBAR_BG = 'NAVBAR_BG';
export const SIDEBAR_BG = 'SIDEBAR_BG';
export const THEME = 'THEME';
export const DIRECTION = 'DIRECTION';
export const SIDEBAR_POSITION = 'SIDEBAR_POSITION';
export const HEADER_POSITION = 'HEADER_POSITION';
export const LAYOUT = 'LAYOUT';
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE';

// USER ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const PASSWORD_SET_SUCCESS = 'PASSWORD_SET_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER_PROFILE_PHOTO = 'DELETE_USER_PROFILE_PHOTO';
export const REFRESH_USER_TOKENS = 'REFRESH_USER_TOKENS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

//MANAGE USERS ACTIONS
export const GET_MANAGE_USERS = 'GET_MANAGE_USERS';
export const GET_MANAGE_USERS_SUCCESS = 'GET_MANAGE_USERS_SUCCESS';
export const GET_MANAGE_USERS_ERROR = 'GET_MANAGE_USERS_ERROR';

// SNACKBAR
export const SET_SNACKBAR_SUCCESS = 'SET_SNACKBAR_SUCCESS';

// DATA CLOUD
export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';

export const GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';

export const GET_CONTACTS_HISTORY_REQUEST = 'GET_CONTACTS_HISTORY_REQUEST';
export const GET_CONTACTS_HISTORY_SUCCESS = 'GET_CONTACTS_HISTORY_SUCCESS';

export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

export const EDIT_CONTACT_REQUEST = 'EDIT_CONTACT_REQUEST';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_ERROR = 'EDIT_CONTACT_ERROR';

export const CHANGE_PASSWORD_DATA_CLOUD_REQUEST = 'CHANGE_PASSWORD_DATACLOUD_REQUEST';
export const CHANGE_PASSWORD_DATA_CLOUD_SUCCESS = 'CHANGE_PASSWORD_DATACLOUD_SUCCESS';
export const CHANGE_PASSWORD_DATA_CLOUD_ERROR = 'CHANGE_PASSWORD_DATACLOUD_ERROR';

// DEALERS REQUESTS
export const GET_DEALERS_REQUESTS = 'GET_DEALERS_REQUESTS';
export const GET_DEALERS_REQUESTS_SUCCESS = 'GET_DEALERS_REQUESTS_SUCCESS';

export const GET_DEALERS_REQUEST = 'GET_DEALERS_REQUEST';
export const GET_DEALERS_REQUEST_SUCCESS = 'GET_DEALERS_REQUEST_SUCCESS';

export const EDIT_DEALERS_REQUEST = 'EDIT_DEALERS_REQUEST';
export const EDIT_DEALERS_REQUEST_SUCCESS = 'EDIT_DEALERS_REQUEST_SUCCESS';
export const EDIT_DEALERS_REQUEST_ERROR = 'EDIT_DEALERS_REQUEST_ERROR';

export const DELETE_DEALERS_REQUEST = 'DELETE_DEALERS_REQUEST';
export const DELETE_DEALERS_REQUEST_SUCCESS = 'DELETE_DEALERS_REQUEST_SUCCESS';
export const DELETE_DEALERS_REQUEST_ERROR = 'DELETE_DEALERS_REQUEST_ERROR';

// DEALERS LEADS
export const GET_DEALERS_LEADS_REQUEST = 'GET_DEALERS_LEADS_REQUEST';
export const GET_DEALERS_LEADS_SUCCESS = 'GET_DEALERS_LEADS_SUCCESS';

export const GET_DEALERS_LEAD_REQUEST = 'GET_DEALERS_LEAD_REQUEST';
export const GET_DEALERS_LEAD_SUCCESS = 'GET_DEALERS_LEAD_SUCCESS';

export const EDIT_DEALERS_LEAD_REQUEST = 'EDIT_DEALERS_LEAD_REQUEST';
export const EDIT_DEALERS_LEAD_SUCCESS = 'EDIT_DEALERS_LEAD_SUCCESS';
export const EDIT_DEALERS_LEAD_ERROR = 'EDIT_DEALERS_LEAD_ERROR';

export const DELETE_DEALERS_LEAD = 'DELETE_DEALERS_LEAD';
export const DELETE_DEALERS_LEAD_SUCCESS = 'DELETE_DEALERS_LEAD_SUCCESS';
export const DELETE_DEALERS_LEAD_ERROR = 'DELETE_DEALERS_LEAD_ERROR';

// DISTRIBUTORS
export const GET_DISTRIBUTORS = 'GET_DISTRIBUTORS';
export const GET_DISTRIBUTORS_SUCCESS = 'GET_DISTRIBUTORS_SUCCESS';

export const GET_DISTRIBUTOR = 'GET_DISTRIBUTOR';
export const GET_DISTRIBUTOR_SUCCESS = 'GET_DISTRIBUTOR_SUCCESS';

export const EDIT_DISTRIBUTOR = 'EDIT_DISTRIBUTOR ';
export const EDIT_DISTRIBUTOR_SUCCESS = 'EDIT_DISTRIBUTOR_SUCCESS';
export const EDIT_DISTRIBUTOR_ERROR = 'EDIT_DISTRIBUTOR_ERROR';

export const DELETE_DISTRIBUTOR = 'EDIT_DISTRIBUTOR ';
export const DELETE_DISTRIBUTOR_SUCCESS = 'EDIT_DISTRIBUTOR_SUCCESS';
export const DELETE_DISTRIBUTOR_ERROR = 'DELETE_DISTRIBUTOR_ERROR';

// DISTRIBUTORS REQUESTS
export const GET_DISTRIBUTORS_REQUESTS = 'GET_DISTRIBUTORS_REQUESTS';
export const GET_DISTRIBUTORS_REQUESTS_SUCCESS = 'GET_DISTRIBUTORS_REQUESTS_SUCCESS';

export const GET_DISTRIBUTOR_REQUEST = 'GET_DISTRIBUTOR_REQUEST';
export const GET_DISTRIBUTOR_REQUEST_SUCCESS = 'GET_DISTRIBUTOR_REQUEST_SUCCESS';

export const EDIT_DISTRIBUTOR_REQUEST = 'EDIT_DISTRIBUTOR_REQUEST ';
export const EDIT_DISTRIBUTOR_REQUEST_SUCCESS = 'EDIT_DISTRIBUTOR_REQUEST_SUCCESS';
export const EDIT_DISTRIBUTOR_REQUEST_ERROR = 'EDIT_DISTRIBUTOR_REQUEST_ERROR';

export const DELETE_DISTRIBUTOR_REQUEST = 'EDIT_DISTRIBUTOR_REQUEST ';
export const DELETE_DISTRIBUTOR_REQUEST_SUCCESS = 'EDIT_DISTRIBUTOR_REQUEST_SUCCESS';
export const DELETE_DISTRIBUTOR_REQUEST_ERROR = 'DELETE_DISTRIBUTOR_REQUEST_ERROR';

// export const CHANGE_PASSWORD_DATA_CLOUD_REQUEST = 'CHANGE_PASSWORD_DATACLOUD_REQUEST';
// export const CHANGE_PASSWORD_DATA_CLOUD_SUCCESS = 'CHANGE_PASSWORD_DATACLOUD_SUCCESS';
// export const CHANGE_PASSWORD_DATA_CLOUD_ERROR = 'CHANGE_PASSWORD_DATACLOUD_ERROR';

// MODAL ACTIONS
export const TOGGLE_GLOBAL_MODAL = 'TOGGLE_GLOBAL_MODAL';
// GLOBAL LOADER
export const SET_GLOBAL_LOADER = 'SET_GLOBAL_LOADER';
export const SET_CONTENT_LOADER = 'SET_CONTENT_LOADER';

// UPLOAD PROGRESS
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const CLEAR_PROGRESS = 'CLEAR_PROGRESS';

// DEALERS_LOCATIONS
export const GET_DEALERS_LOCATIONS = 'GET_DEALERS_LOCATIONS';
export const GET_DEALERS_LOCATIONS_SUCCESS = 'GET_DEALERS_LOCATIONS_SUCCESS';
export const GET_DEALERS_LOCATIONS_ERROR = 'GET_DEALERS_LOCATIONS_ERROR';

export const GET_DEALER_LOCATIONS = 'GET_DEALER_LOCATIONS';
export const GET_DEALER_LOCATIONS_SUCCESS = 'GET_DEALER_LOCATIONS_SUCCESS';
export const GET_DEALER_LOCATIONS_ERROR = 'GET_DEALER_LOCATIONS_ERROR';

export const EDIT_DEALER_LOCATIONS = 'EDIT_DEALER_LOCATIONS';
export const EDIT_DEALER_LOCATIONS_SUCCESS = 'EDIT_DEALER_LOCATIONS_SUCCESS';
export const EDIT_DEALER_LOCATIONS_ERROR = 'EDIT_DEALER_LOCATIONS_ERROR';

export const DELETE_DEALER_LOCATIONS = 'DELETE_DEALER_LOCATIONS';
export const DELETE_DEALER_LOCATIONS_SUCCESS = 'DELETE_DEALER_LOCATIONS_SUCCESS';
export const DELETE_DEALER_LOCATIONS_ERROR = 'DELETE_DEALER_LOCATIONS_ERROR';
